// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// datarateDetector //
// ---------------- //

#define datarateDetector_wrap_target 0
#define datarateDetector_wrap 13
#define datarateDetector_pio_version 0

static const uint16_t datarateDetector_program_instructions[] = {
            //     .wrap_target
    0xa02b, //  0: mov    x, ~null
    0x2020, //  1: wait   0 pin, 0
    0x20a0, //  2: wait   1 pin, 0
    0x0045, //  3: jmp    x--, 5
    0x0008, //  4: jmp    8
    0x00c3, //  5: jmp    pin, 3
    0x00ca, //  6: jmp    pin, 10
    0x0046, //  7: jmp    x--, 6
    0xc020, //  8: irq    wait 0
    0x0000, //  9: jmp    0
    0xa029, // 10: mov    x, ~x
    0x4020, // 11: in     x, 32
    0x8020, // 12: push   block
    0x0000, // 13: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program datarateDetector_program = {
    .instructions = datarateDetector_program_instructions,
    .length = 14,
    .origin = 0,
    .pio_version = datarateDetector_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config datarateDetector_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + datarateDetector_wrap_target, offset + datarateDetector_wrap);
    return c;
}

#include <hardware/timer.h>
static inline void datarateDetector_program_init(PIO pio, int dataPin) {
    pio_add_program(pio, &datarateDetector_program);
    pio_gpio_init(pio, dataPin);
    pio_sm_set_consecutive_pindirs(pio, 0, dataPin, 1, false);
    pio_sm_config c = datarateDetector_program_get_default_config(0);
    sm_config_set_in_pins(&c, dataPin);
    sm_config_set_in_pin_count(&c, 1);
    sm_config_set_jmp_pin(&c, dataPin);
    sm_config_set_clkdiv(&c, 1);
    pio_sm_init(pio, 0, 0, &c);
    pio_sm_clear_fifos(pio, 0);
    pio_sm_set_enabled(pio, 0, true);
    //PIO should start to spew out data very quick now...
}
static inline void datarateDetector_program_exit(PIO pio) {
    pio_sm_set_enabled(pio, 0, false);
    pio_sm_unclaim(pio, 0);
}
//gets a value from the FIFO
//exits if timeout is reached with true
//otherwise sets destination to FIFO value and returns with false
static bool datarateDetector_pull(PIO pio, uint32_t* destination, uint64_t timeout) {
    if (destination == NULL) return false;
    while (timeout > time_us_64()) {
        if (pio_sm_get_rx_fifo_level(pio, 0) > 0) {
            *destination = pio_sm_get(pio, 0);
            return false;
        }
    }
    return true;
}

#endif

